#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const repositoryRoot = path.resolve(root, '..', '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));

function literal(value) {
	return JSON.stringify(value);
}

function typeFor(schema, depth = 0) {
	if (!schema || schema === true) return 'JsonValue';
	if (Object.prototype.hasOwnProperty.call(schema, 'const')) return literal(schema.const);
	if (schema.enum) return schema.enum.map(literal).join(' | ');
	if (Array.isArray(schema.type)) return schema.type.map((type) => typeFor({ ...schema, type }, depth)).join(' | ');
	if (schema.type === 'string') return 'string';
	if (schema.type === 'number' || schema.type === 'integer') return 'number';
	if (schema.type === 'boolean') return 'boolean';
	if (schema.type === 'null') return 'null';
	if (schema.type === 'array') return `Array<${typeFor(schema.items, depth + 1)}>`;
	if (schema.type === 'object') {
		const required = new Set(schema.required || []);
		const properties = Object.entries(schema.properties || {}).map(([name, child]) => {
			const optional = required.has(name) ? '' : '?';
			return `${JSON.stringify(name)}${optional}: ${typeFor(child, depth + 1)};`;
		});
		const body = `{ ${properties.join(' ')} }`;
		if (schema.additionalProperties === true) return `${body} & Record<string, JsonValue>`;
		if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
			return `${body} & Record<string, ${typeFor(schema.additionalProperties, depth + 1)}>`;
		}
		return body;
	}
	return 'JsonValue';
}

const schemas = manifest.contracts.map((contract) => ({
	...contract,
	document: JSON.parse(fs.readFileSync(path.join(root, contract.file), 'utf8')),
}));

const ts = [
	'// Generated by tools/generate-types.cjs. Do not edit directly.',
	'export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };',
	'',
	...schemas.flatMap((item) => [`export type ${item.type} = ${typeFor(item.document)};`, '']),
	'export const contractSchemas = {',
	...schemas.map((item) => `  ${item.name}: ${JSON.stringify(item.schema)},`),
	'} as const;',
	'',
].join('\n');

const phpClasses = schemas.map((item) => {
	return [
		`final class ${item.type} {`,
		`\tpublic const SCHEMA = '${item.schema}';`,
		'\t/** @param array<string, mixed> $value */',
		'\tpublic function __construct( public readonly array $value ) {}',
		'}',
	].join('\n');
}).join('\n\n');

const php = [
	'<?php',
	'// Generated by tools/generate-types.cjs. Do not edit directly.',
	'namespace Kiwe\\SEAM\\Contracts;',
	'',
	phpClasses,
	'',
].join('\n');

const seamTokenSource = fs.readFileSync(
	path.join(repositoryRoot, 'wp-content/mu-plugins/dsa/includes/Design/Seam_Token_Service.php'),
	'utf8'
);
const packageEntrySource = fs.readFileSync(path.join(repositoryRoot, 'wp-content/mu-plugins/dsa/dsa.php'), 'utf8');
const kiweVersion = packageEntrySource.match(/define\(\s*'DSA_VERSION'\s*,\s*'([^']+)'\s*\)/)?.[1] || '';
if (!kiweVersion) throw new Error('Could not derive Kiwe DSA_VERSION for the generated token catalog.');
const tokenPattern = /self::token\(\s*'([^']+)'\s*,\s*'([^']*)'\s*,\s*'([^']+)'/g;
const tokens = {};
let tokenMatch;
while ((tokenMatch = tokenPattern.exec(seamTokenSource))) {
	const [, name, value, domain] = tokenMatch;
	tokens[name] = { value, domain, cssVariable: `--kiwe-${name}` };
}
const tokenCatalog = `${JSON.stringify({ schema: 'kiwe.seam-token-catalog.v1', pluginVersion: kiweVersion, tokens }, null, 2)}\n`;

const outputs = new Map([
	[path.join(root, 'generated', 'contracts.ts'), ts],
	[path.join(root, 'generated', 'Contract_Types.php'), php],
	[path.join(root, 'generated', 'kiwe-token-catalog.json'), tokenCatalog],
]);
const check = process.argv.includes('--check');
let drift = false;

for (const [file, content] of outputs) {
	if (check) {
		const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
		if (existing !== content) {
			console.error(`Generated contract type drift: ${path.relative(root, file)}`);
			drift = true;
		}
	} else {
		fs.mkdirSync(path.dirname(file), { recursive: true });
		fs.writeFileSync(file, content);
		console.log(`Generated ${path.relative(root, file)}`);
	}
}

if (drift) process.exit(1);
if (check) console.log('Generated SEAM contract types are current.');
